In [1]:
import numpy as np

In [2]:
ar1=np.array(6)

In [3]:
type(ar1)

numpy.ndarray

In [4]:
ar1

array(6)

In [5]:
ar2=np.array([[1,2,3,4],[2,4,3,1]])

In [6]:
ar2

array([[1, 2, 3, 4],
       [2, 4, 3, 1]])

In [7]:
zero_array=np.zeros(2)

In [8]:
zero_array

array([0., 0.])

In [9]:
zero_array=np.zeros((4,4))

In [10]:
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
zero_array=np.ones((4,4))

In [12]:
zero_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
ar4=np.arange(6)

In [14]:
ar4

array([0, 1, 2, 3, 4, 5])

In [15]:
ar5=np.arange(2,15,2)

In [16]:
ar5

array([ 2,  4,  6,  8, 10, 12, 14])

In [17]:
ar6=np.transpose(ar2)

In [18]:
ar6

array([[1, 2],
       [2, 4],
       [3, 3],
       [4, 1]])

In [19]:
ar7=np.ravel(ar6)

In [20]:
ar7

array([1, 2, 2, 4, 3, 3, 4, 1])

In [21]:
a1=np.array([1,2])
a2=np.array([4,5])

In [22]:
a1

array([1, 2])

In [23]:
a2

array([4, 5])

In [24]:
concat=np.concatenate((a1,a2))

In [25]:
concat

array([1, 2, 4, 5])

In [26]:
hori=np.hstack((a1,a2))

In [27]:
hori

array([1, 2, 4, 5])

In [28]:
vert=np.vstack((a1,a2))

In [29]:
vert

array([[1, 2],
       [4, 5]])

# DETERMINANT

In [30]:
mat=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [31]:
mat

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [32]:
det_of_mat=np.linalg.det(mat)

In [33]:
det_of_mat

0.0

In [34]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
det_of_mat1=np.linalg.det(mat1)

In [37]:
det_of_mat1

0.0

# INVERSE

In [42]:
mat2=np.array([[1,2],[4,5]])

In [43]:
mat2

array([[1, 2],
       [4, 5]])

In [45]:
det_of_mat2=np.linalg.det(mat2)

In [46]:
det_of_mat2

-2.9999999999999996

In [48]:
inverse=np.linalg.inv(mat2)

In [49]:
inverse

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [50]:
dense=np.array([[2,6,3,2],[6,11,4,6],[17,2,73,17],[2,6,3,2]])

In [51]:
dense

array([[ 2,  6,  3,  2],
       [ 6, 11,  4,  6],
       [17,  2, 73, 17],
       [ 2,  6,  3,  2]])

In [52]:
from scipy.sparse import csr_matrix

In [53]:
sparse=csr_matrix(dense)

In [54]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Row format>

In [55]:
print(sparse)

  (0, 0)	2
  (0, 1)	6
  (0, 2)	3
  (0, 3)	2
  (1, 0)	6
  (1, 1)	11
  (1, 2)	4
  (1, 3)	6
  (2, 0)	17
  (2, 1)	2
  (2, 2)	73
  (2, 3)	17
  (3, 0)	2
  (3, 1)	6
  (3, 2)	3
  (3, 3)	2
