In [1]:
import numpy as np

In [2]:
ar1=np.array(6)

In [4]:
type(ar1)

numpy.ndarray

In [5]:
ar1

array(6)

In [13]:
ar2=np.array([[1,2,3,4],[2,4,3,1]])

In [14]:
ar2

array([[1, 2, 3, 4],
       [2, 4, 3, 1]])

In [15]:
zero_array=np.zeros(2)

In [16]:
zero_array

array([0., 0.])

In [19]:
zero_array=np.zeros((4,4))

In [20]:
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
zero_array=np.ones((4,4))

In [22]:
zero_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
ar4=np.arange(6)

In [27]:
ar4

array([0, 1, 2, 3, 4, 5])

In [29]:
ar5=np.arange(2,15,2)

In [30]:
ar5

array([ 2,  4,  6,  8, 10, 12, 14])

In [33]:
ar6=np.transpose(ar2)

In [34]:
ar6

array([[1, 2],
       [2, 4],
       [3, 3],
       [4, 1]])

In [35]:
ar7=np.ravel(ar6)

In [36]:
ar7

array([1, 2, 2, 4, 3, 3, 4, 1])

In [38]:
a1=np.array([1,2])
a2=np.array([4,5])

In [39]:
a1

array([1, 2])

In [40]:
a2

array([4, 5])

In [41]:
concat=np.concatenate((a1,a2))

In [42]:
concat

array([1, 2, 4, 5])

In [43]:
hori=np.hstack((a1,a2))

In [44]:
hori

array([1, 2, 4, 5])

In [45]:
vert=np.vstack((a1,a2))

In [46]:
vert

array([[1, 2],
       [4, 5]])