In [1]:
import numpy as np

In [2]:
ar1=np.array(6)

In [3]:
ar1

array(6)

In [4]:
ar2=np.array([1,2,3,4,5])

In [5]:
ar2

array([1, 2, 3, 4, 5])

In [6]:
zero_array=np.zeros(2)

In [7]:
zero_array

array([0., 0.])

In [8]:
one_array=np.ones((2,3))

In [9]:
one_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ar4=np.arange(6)

In [11]:
ar4

array([0, 1, 2, 3, 4, 5])

In [12]:
ar5=np.arange(2,19,2)

In [13]:
ar5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
ar6=np.transpose(ar5)

In [15]:
ar6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
ar7=np.ravel(ar6)

In [17]:
ar7

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
ar8=np.array([2,2])
ar9=np.array([3,4])

In [19]:
ar8

array([2, 2])

In [20]:
concat=np.concatenate((ar8,ar9))

In [21]:
concat

array([2, 2, 3, 4])

In [22]:
hori = np.vstack((ar8,ar9))

In [23]:
hori

array([[2, 2],
       [3, 4]])

In [24]:
# Create a 2x3 matrix with specific values
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
type(matrix)

numpy.ndarray

In [26]:
determinant = np.linalg.det(matrix)

In [27]:
determinant

-9.51619735392994e-16

In [28]:
inverse = np.linalg.inv(matrix)

In [29]:
inverse

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [30]:
# Create a 4x4 identity matrix
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
# Create a 3x3 matrix with random values between 0 and 1
random_matrix = np.random.rand(3, 3)

print(random_matrix)

[[0.23443493 0.44780135 0.76253835]
 [0.27633001 0.13907656 0.48485467]
 [0.52461844 0.88112409 0.82781421]]


In [32]:
# 1. Matrix Addition and Subtraction

# Define two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix addition
sum_matrix = matrix1 + matrix2

# Matrix subtraction
diff_matrix = matrix1 - matrix2

print("Sum of matrices:\n", sum_matrix)
print("Difference of matrices:\n", diff_matrix)

Sum of matrices:
 [[ 6  8]
 [10 12]]
Difference of matrices:
 [[-4 -4]
 [-4 -4]]


In [33]:
# 2.Matrix Multiplication

# Define two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
product_matrix = matrix1 @ matrix2  # or np.dot(matrix1, matrix2)

print("Product of matrices:\n", product_matrix)

Product of matrices:
 [[19 22]
 [43 50]]


In [34]:
# 3.Element-wise Multiplication

# Define two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Element-wise multiplication
elementwise_product = matrix1 * matrix2

print("Element-wise product:\n", elementwise_product)

Element-wise product:
 [[ 5 12]
 [21 32]]


In [35]:
# 4.Transpose of a Matrix

# Define a matrix
matrix = np.array([[1, 2], [3, 4]])

# Transpose of the matrix
transpose_matrix = matrix.T

print("Transpose of the matrix:\n", transpose_matrix)

Transpose of the matrix:
 [[1 3]
 [2 4]]


In [36]:
# 5.Inverse of a Matrix

# Define a square matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute the inverse
inverse_matrix = np.linalg.inv(matrix)

print("Inverse of the matrix:\n", inverse_matrix)

Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
# 6.Eigenvalues and Eigenvectors

# Define a square matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [38]:
# 7.Matrix Norm

# Define a matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute the Frobenius norm (default)
frobenius_norm = np.linalg.norm(matrix)

print("Frobenius norm of the matrix:", frobenius_norm)

Frobenius norm of the matrix: 5.477225575051661


In [39]:
# 8.Singular Value Decomposition (SVD)

# Define a matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute the SVD
U, S, Vt = np.linalg.svd(matrix)

print("U matrix:\n", U)
print("S (singular values):\n", S)
print("Vt matrix:\n", Vt)

U matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S (singular values):
 [5.4649857  0.36596619]
Vt matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [40]:
# 9.Matrix Rank

# Define a matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute the rank
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)

Rank of the matrix: 2


In [41]:
# These functions cover a wide range of matrix operations and are very useful 
# for various mathematical and scientific computing tasks.

In [42]:
Dense = np.array([[1,0,3,0],[0,0,0,6],[0,5,6,7,],[0,0,1,1]])

In [43]:
Dense

array([[1, 0, 3, 0],
       [0, 0, 0, 6],
       [0, 5, 6, 7],
       [0, 0, 1, 1]])

In [44]:
from scipy.sparse import csr_matrix

In [45]:
sparse= csr_matrix(Dense)

In [46]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

In [47]:
print(sparse)

  (0, 0)	1
  (0, 2)	3
  (1, 3)	6
  (2, 1)	5
  (2, 2)	6
  (2, 3)	7
  (3, 2)	1
  (3, 3)	1


In [48]:
# Create a 4x4 sparse matrix
data = np.array([1, 2, 3, 4, 5, 6, 7, 8])
row_indices = np.array([0, 0, 1, 1, 2, 2, 3, 3])
col_indices = np.array([0, 1, 1, 2, 2, 3, 3, 0])

# Create the sparse matrix in Compressed Sparse Row (CSR) format
sparse_matrix = csr_matrix((data, (row_indices, col_indices)), shape=(4, 4))

print(sparse_matrix)

  (0, 0)	1
  (0, 1)	2
  (1, 1)	3
  (1, 2)	4
  (2, 2)	5
  (2, 3)	6
  (3, 0)	8
  (3, 3)	7


In [49]:
print(sparse_matrix.toarray()) 
# Convert sparse matrix to dense format for visualization

[[1 2 0 0]
 [0 3 4 0]
 [0 0 5 6]
 [8 0 0 7]]
